export const INITAL_LOAD_LOGIN = 'INITAL_LOAD_LOGIN';
export const INITAL_DATA_LOGIN = 'INITAL_DATA_LOGIN';
export const INITAL_HIDE_LOGIN = 'INITAL_HIDE_LOGIN';

export const INITALGET_LOAD_PLAN = 'INITALGET_LOAD_PLAN';
export const INITALGET_DATA_PLAN = 'INITALGET_DATA_PLAN';
export const INITALGET_HIDE_PLAN = 'INITALGET_HIDE_PLAN';
